# HW 10

# Team: DSDA

In [59]:
import pandas as pd
import numpy as np

s1 = pd.read_csv('based_on_mean.csv')
s2 = pd.read_csv('based_on_mode.csv')
s3 = pd.read_csv('based_on_mode_1.csv')
s4 = pd.read_csv('4genres.csv')
s5 = pd.read_csv('hw8_mat_fac.csv')
s6 = pd.read_csv('lr_answer.csv')
s7 = pd.read_csv('dt_answer.csv')
s8 = pd.read_csv('rf_answer.csv')
s9 = pd.read_csv('gbt_answer.csv')
s10 = pd.read_csv('lr_answer_six.csv')
s11 = pd.read_csv('dt_answer_six.csv')
s12 = pd.read_csv('rf_answer_six.csv')
s13 = pd.read_csv('gbt_answer_six.csv')

In [60]:
s1.head()

TrackID  Predictor
0  199810_208019          0
1   199810_74139          0
2    199810_9903          0
3  199810_242681          0
4   199810_18515          1

In [61]:
# save the scores for each of these submissions
p1 = 0.85745
p2 = 0.84909
p3 = 0.77711
p4 = 0.84402
p5 = 0.67488
p6 = 0.85771
p7 = 0.85756
p8 = 0.85756
p9 = 0.85753
p10 = 0.85595
p11 = 0.85481
p12 = 0.85709
p13 = 0.85539

In [62]:
S = [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13]
for i in range(len(S)):
    S[i].drop(columns='TrackID', inplace=True)

In [63]:
for i in range(len(S)):
    S[i].rename(columns={"Predictor":"s"+str(i+1)}, inplace=True)

In [64]:
s1.head()

s1
0   0
1   0
2   0
3   0
4   1

In [65]:
for i in range(len(S)):
    S[i]['s'+str(i+1)] = 2.0*S[i]['s'+str(i+1)] - 1.0

In [66]:
S

[         s1
 0      -1.0
 1      -1.0
 2      -1.0
 3      -1.0
 4       1.0
 ...     ...
 119995 -1.0
 119996 -1.0
 119997  1.0
 119998 -1.0
 119999  1.0
 
 [120000 rows x 1 columns],
          s2
 0      -1.0
 1      -1.0
 2      -1.0
 3      -1.0
 4       1.0
 ...     ...
 119995 -1.0
 119996 -1.0
 119997  1.0
 119998 -1.0
 119999  1.0
 
 [120000 rows x 1 columns],
          s3
 0      -1.0
 1       1.0
 2      -1.0
 3      -1.0
 4       1.0
 ...     ...
 119995 -1.0
 119996 -1.0
 119997  1.0
 119998 -1.0
 119999  1.0
 
 [120000 rows x 1 columns],
          s4
 0      -1.0
 1       1.0
 2      -1.0
 3      -1.0
 4       1.0
 ...     ...
 119995 -1.0
 119996 -1.0
 119997  1.0
 119998 -1.0
 119999  1.0
 
 [120000 rows x 1 columns],
          s5
 0       1.0
 1      -1.0
 2      -1.0
 3      -1.0
 4       1.0
 ...     ...
 119995  1.0
 119996 -1.0
 119997  1.0
 119998 -1.0
 119999  1.0
 
 [120000 rows x 1 columns],
          s6
 0      -1.0
 1      -1.0
 2      -1.0
 3      -1.0
 4   

In [67]:
s_mat = pd.concat(S, axis=1)

In [68]:
s_mat.head()

s1   s2   s3   s4   s5   s6   s7   s8   s9  s10  s11  s12  s13
0 -1.0 -1.0 -1.0 -1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [69]:
s_mat.shape

(120000, 13)

In [77]:
s_mat.shape[0]

120000

In [71]:
stx = np.zeros((13,1))

In [73]:
len(stx)

13

In [74]:
P = [p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13]

In [78]:
N=s_mat.shape[0]
for i in range(len(stx)):
    stx[i] = N*((2.0*P[i]) - 1.0)

In [79]:
stx

array([[85788. ],
       [83781.6],
       [66506.4],
       [82564.8],
       [41971.2],
       [85850.4],
       [85814.4],
       [85814.4],
       [85807.2],
       [85428. ],
       [85154.4],
       [85701.6],
       [85293.6]])

In [81]:
s_matrix = s_mat.to_numpy()

In [83]:
type(s_matrix)

numpy.ndarray

In [84]:
type(stx)

numpy.ndarray

In [88]:
sts = np.matmul(s_matrix.T,s_matrix)


In [89]:
sts

array([[120000., 114728.,  77324.,  85362.,  34834., 118094., 119810.,
        119810., 119742., 116954., 116380., 119110., 116552.],
       [114728., 120000.,  82596.,  83534.,  34118., 112822., 114538.,
        114538., 114470., 111682., 112024., 113946., 112196.],
       [ 77324.,  82596., 120000.,  74706.,  29002.,  75418.,  77134.,
         77134.,  77066.,  74278.,  79880.,  77254.,  79492.],
       [ 85362.,  83534.,  74706., 120000.,  34396.,  85332.,  85384.,
         85384.,  85336.,  85480.,  85866.,  85344.,  85642.],
       [ 34834.,  34118.,  29002.,  34396., 120000.,  34968.,  34844.,
         34844.,  34820.,  34796.,  34946.,  34816.,  34898.],
       [118094., 112822.,  75418.,  85332.,  34968., 120000., 118284.,
        118284., 118208., 118452., 114906., 117860., 115182.],
       [119810., 114538.,  77134.,  85384.,  34844., 118284., 120000.,
        120000., 119908., 117144., 116530., 119292., 116678.],
       [119810., 114538.,  77134.,  85384.,  34844., 118284., 

In [91]:
sts_inv = np.linalg.inv(sts)

In [92]:
sts_inv

array([[ 2.75116631e-03, -9.44981769e-05,  5.98642409e-07,
        -2.09906561e-06, -2.33748808e-07,  4.16404666e-06,
        -2.61501408e-04, -2.11306221e-03, -3.37799075e-04,
         5.15969935e-07,  4.14571355e-05, -4.65186390e-06,
        -4.74816228e-05],
       [-9.44981769e-05,  1.08399548e-04, -1.34924710e-05,
         1.13212926e-06, -6.42257743e-08,  7.61298631e-08,
        -2.24929573e-05,  2.16525588e-05,  1.61413096e-06,
        -3.33009956e-07,  4.10472739e-06,  2.24228666e-06,
        -8.24331092e-06],
       [ 5.98642409e-07, -1.34924710e-05,  1.81886247e-05,
        -5.26090035e-06, -4.70355364e-07,  7.11337885e-07,
         5.84510654e-05, -5.54050262e-05,  3.54936295e-06,
         4.66602337e-06, -9.21013936e-06,  2.35213002e-06,
        -6.35378974e-07],
       [-2.09906561e-06,  1.13212926e-06, -5.26090035e-06,
         1.93187761e-05, -1.27801433e-06, -6.19491484e-07,
         3.50160894e-05, -3.14259476e-05, -1.45978819e-06,
        -7.73596413e-06, -5.69041530e

In [93]:
als = np.matmul(sts_inv, stx)

In [94]:
als

array([[ -5.31753354],
       [  0.05159532],
       [  0.06522518],
       [  0.29440381],
       [  0.11823171],
       [  0.54385074],
       [-14.42471852],
       [  9.37252472],
       [  0.22520956],
       [  0.06545242],
       [ -0.07767324],
       [  0.03231827],
       [  0.15326898]])

In [95]:
s_ensemble_1 = np.matmul(s_matrix, als)

In [96]:
s_ensemble_1

array([[ 9.13430801],
       [ 9.61710257],
       [ 8.89784459],
       ...,
       [-8.89784459],
       [ 8.89784459],
       [-8.89784459]])

In [97]:
len(s_ensemble_1)

120000

In [99]:
s_ensemble_1[0:6]

array([[ 9.13430801],
       [ 9.61710257],
       [ 8.89784459],
       [ 8.89784459],
       [-8.89784459],
       [-8.89784459]])

In [103]:
s_ensemble_1[0:6].sort(ascending=False)

TypeError: 'ascending' is an invalid keyword argument for sort()

In [101]:
s_ensemble_1[0:6]

array([[ 9.13430801],
       [ 9.61710257],
       [ 8.89784459],
       [ 8.89784459],
       [-8.89784459],
       [-8.89784459]])

In [185]:
ans_1 = pd.read_csv('lr_answer.csv')

In [186]:
ans_1.head()

TrackID  Predictor
0  199810_208019        0.0
1   199810_74139        0.0
2    199810_9903        0.0
3  199810_242681        0.0
4   199810_18515        1.0

In [187]:
for i in range(len(ans_1)):
    ans_1['Predictor'][i] = s_ensemble_1[i]

/Users/Sivankit/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [188]:
ans_1.head()

TrackID  Predictor
0  199810_208019   9.134308
1   199810_74139   9.617103
2    199810_9903   8.897845
3  199810_242681   8.897845
4   199810_18515  -8.897845

In [189]:
ans_1['Predictor'][0:6]

0    9.134308
1    9.617103
2    8.897845
3    8.897845
4   -8.897845
5   -8.897845
Name: Predictor, dtype: float64

In [190]:
ans_1['Predictor'][0:6].nlargest(3)

1    9.617103
0    9.134308
2    8.897845
Name: Predictor, dtype: float64

In [191]:
ans_1['Predictor'][0:6].nsmallest(3)

4   -8.897845
5   -8.897845
2    8.897845
Name: Predictor, dtype: float64

In [192]:
ans_1.head(12)

TrackID  Predictor
0   199810_208019   9.134308
1    199810_74139   9.617103
2     199810_9903   8.897845
3   199810_242681   8.897845
4    199810_18515  -8.897845
5   199810_105760  -8.897845
6   199812_276940   8.897845
7   199812_142408  -8.897845
8   199812_130023  -9.134308
9    199812_29189   9.028295
10  199812_223706  -8.897845
11  199812_211361   9.134308

In [193]:
ans_1.tail(12)

TrackID  Predictor
119988    249008_4967  -9.134308
119989  249008_164591  -9.134308
119990  249008_127497   8.897845
119991  249008_165413  -8.897845
119992  249008_197975   9.134308
119993  249008_239621   9.134308
119994  249010_110470  -9.134308
119995   249010_72192   9.134308
119996   249010_86104   8.897845
119997  249010_186634  -8.897845
119998  249010_293818   8.897845
119999  249010_262811  -8.897845

In [194]:
start=0
end=6
while end <=120000:
    ans_1['Predictor'][ans_1['Predictor'][start:end].nlargest(3).index[0:3]] = 1.0
    
    start=end
    end +=6

/Users/Sivankit/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [195]:
ans_1.head(12)

TrackID  Predictor
0   199810_208019   1.000000
1    199810_74139   1.000000
2     199810_9903   1.000000
3   199810_242681   8.897845
4    199810_18515  -8.897845
5   199810_105760  -8.897845
6   199812_276940   1.000000
7   199812_142408  -8.897845
8   199812_130023  -9.134308
9    199812_29189   1.000000
10  199812_223706  -8.897845
11  199812_211361   1.000000

In [196]:
ans_1.tail(12)

TrackID  Predictor
119988    249008_4967  -9.134308
119989  249008_164591  -9.134308
119990  249008_127497   1.000000
119991  249008_165413  -8.897845
119992  249008_197975   1.000000
119993  249008_239621   1.000000
119994  249010_110470  -9.134308
119995   249010_72192   1.000000
119996   249010_86104   1.000000
119997  249010_186634  -8.897845
119998  249010_293818   1.000000
119999  249010_262811  -8.897845

In [197]:
for i in range(len(ans_1)):
    if ans_1['Predictor'][i] != 1.0:
        ans_1['Predictor'][i] = 0.0

/Users/Sivankit/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [198]:
ans_1.head(12)

TrackID  Predictor
0   199810_208019        1.0
1    199810_74139        1.0
2     199810_9903        1.0
3   199810_242681        0.0
4    199810_18515        0.0
5   199810_105760        0.0
6   199812_276940        1.0
7   199812_142408        0.0
8   199812_130023        0.0
9    199812_29189        1.0
10  199812_223706        0.0
11  199812_211361        1.0

In [199]:
ans_1.tail(12)

TrackID  Predictor
119988    249008_4967        0.0
119989  249008_164591        0.0
119990  249008_127497        1.0
119991  249008_165413        0.0
119992  249008_197975        1.0
119993  249008_239621        1.0
119994  249010_110470        0.0
119995   249010_72192        1.0
119996   249010_86104        1.0
119997  249010_186634        0.0
119998  249010_293818        1.0
119999  249010_262811        0.0

In [200]:
ans_1.to_csv('ensemble_1.csv', index=False)

In [201]:
ans_1['Predictor'].value_counts()

0.0    60000
1.0    60000
Name: Predictor, dtype: int64

In [202]:
ans_1.head()

TrackID  Predictor
0  199810_208019        1.0
1   199810_74139        1.0
2    199810_9903        1.0
3  199810_242681        0.0
4   199810_18515        0.0

In [203]:
ans_1['Predictor'] = np.int64(ans_1['Predictor'])

In [204]:
ans_1

TrackID  Predictor
0       199810_208019          1
1        199810_74139          1
2         199810_9903          1
3       199810_242681          0
4        199810_18515          0
...               ...        ...
119995   249010_72192          1
119996   249010_86104          1
119997  249010_186634          0
119998  249010_293818          1
119999  249010_262811          0

[120000 rows x 2 columns]

In [205]:
ans_1.to_csv('ensemble_1.csv', index=False)

Uploading the above generated ensemble csv yields only ~20% score. Therefore, we will now try to swap the 0s and 1s in the csv and make another upload. 

# swap the zeros and ones in predictor

In [1]:
import pandas as pd

df1 = pd.read_csv('ensemble_1.csv')

In [2]:
df1.head()

TrackID  Predictor
0  199810_208019          1
1   199810_74139          1
2    199810_9903          1
3  199810_242681          0
4   199810_18515          0

In [3]:
for i in range(len(df1)):
    if df1['Predictor'][i] == 1:
        df1['Predictor'][i] = 0
    else:
        df1['Predictor'][i] = 1

/Users/Sivankit/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/Sivankit/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [4]:
df1.head()

TrackID  Predictor
0  199810_208019          0
1   199810_74139          0
2    199810_9903          0
3  199810_242681          1
4   199810_18515          1

In [5]:
df1.to_csv('ensemble_1_swapped.csv', index=False)

With this, we were able to achieve 79.5% accuracy on test set on Kaggle. Therefore, this is much better. However, this is still not an improvement over most of our previous scores and we will keep trying to improve the score using more methods. 

For the purposes of HW10, we will submit this result for now. 